package examen;

import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * Fila 3 silla 12
 *
 * @author Irene Sinclair
 */
public class JframeExamen extends javax.swing.JFrame {

    /**
     * Creates new form JframeExamen
     */
    public JframeExamen() {
        this.pack();
        initComponents();
        
        persona.add(new Empleados("Juan", "Perez", "j1234", new Date(100, 01, 15), "Masculino", "Francisco Morazan", "Sistemas", "Analista", 2.5));
        persona.add(new Empleados("Maria", "Lainez", "maria123", new Date(90, 06, 30), "Femenino", "Cortes", "Finanzas", "Cajero", 1));
        persona.add(new Empleados("Lucia", "Gomez", "lugomez1", new Date(75, 10, 23), "Femenino", "Comayagua", "Derecho", "Notaria", 5));
        persona.add(new Clientes("Pablo", "Guevara", "p234", new Date(98, 07, 19), "Masculino", "Comayagua"));
        persona.add(new Clientes("Carla", "Padilla", "carla634", new Date(105, 01, 06), "Femenino", "Cortes"));
        persona.add(new Clientes("Luis", "Amador", "amador234", new Date(87, 05, 17), "Masculino", "Francisco Morazan"));
        
        Tramites t = new Tramites("Acta", "Solicitud de Acta de Nacimiento", new Date(124, 01, 15), "0201198709812");
        Tramites t1 = new Tramites("Solicitud", "Modificacion de Tramite", new Date(123, 04, 18), "0312200007652");
        Tramites t2 = new Tramites("Registro", "Inscripcion de nino", new Date(124, 05, 19), "0123199810678");
        ((Clientes) persona.get(3)).getTramite().add(t);
        ((Clientes) persona.get(4)).getTramite().add(t1);
        ((Clientes) persona.get(5)).getTramite().add(t2);
        System.out.println(persona);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        empleado = new javax.swing.JFrame();
        p_empleado = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        p_infociviles = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tabla1_empleado = new javax.swing.JScrollPane();
        tablainfo = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        tablatramites = new javax.swing.JScrollPane();
        tablatrami = new javax.swing.JTable();
        p_modciviles = new javax.swing.JPanel();
        mostrarid = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        tf_nombre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tf_apellido = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tf_clave = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jCalendar2 = new com.toedter.calendar.JCalendar();
        jTextField4 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        civil = new javax.swing.JFrame();
        p_civil = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        t_personal = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1_civil = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        tabla2_empleado1 = new javax.swing.JScrollPane();
        tablacivil = new javax.swing.JTable();
        p_gestion = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        tf_nombrecivil = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tp_descripcion = new javax.swing.JTextPane();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        login = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        clave = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        empleado.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        p_empleado.setBackground(new java.awt.Color(204, 255, 255));
        p_empleado.setPreferredSize(new java.awt.Dimension(720, 485));
        p_empleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_empleadoMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Sitka Subheading", 3, 24)); // NOI18N
        jLabel4.setText("B I E N V E N I D O :");

        p_infociviles.setBackground(new java.awt.Color(204, 204, 255));

        jLabel5.setFont(new java.awt.Font("Segoe UI Historic", 3, 12)); // NOI18N
        jLabel5.setText("Informacion de Civiles: ");

        tablainfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre Completo", "N. Identidad", "Fecha Nacimiento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabla1_empleado.setViewportView(tablainfo);

        jLabel6.setFont(new java.awt.Font("Segoe UI Historic", 3, 12)); // NOI18N
        jLabel6.setText("Tramites:");

        tablatrami.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre Tramite", "Descripcion", "Fecha", "Numero de Identidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablatramites.setViewportView(tablatrami);

        javax.swing.GroupLayout p_infocivilesLayout = new javax.swing.GroupLayout(p_infociviles);
        p_infociviles.setLayout(p_infocivilesLayout);
        p_infocivilesLayout.setHorizontalGroup(
            p_infocivilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_infocivilesLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(p_infocivilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(p_infocivilesLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(p_infocivilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tabla1_empleado, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
                            .addComponent(tablatramites))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        p_infocivilesLayout.setVerticalGroup(
            p_infocivilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_infocivilesLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabla1_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(tablatramites, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Informacion Civiles", p_infociviles);

        p_modciviles.setBackground(new java.awt.Color(204, 204, 255));

        mostrarid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        mostrarid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostraridActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Historic", 3, 14)); // NOI18N
        jLabel7.setText("Nombre:");

        jLabel8.setFont(new java.awt.Font("Segoe UI Historic", 3, 14)); // NOI18N
        jLabel8.setText("Apellido:");

        jLabel9.setFont(new java.awt.Font("Segoe UI Historic", 3, 14)); // NOI18N
        jLabel9.setText("Contraseña:");

        tf_clave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_claveActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI Historic", 3, 14)); // NOI18N
        jLabel10.setText("Sexo:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Femenino", "Masculino", " " }));

        jLabel12.setFont(new java.awt.Font("Segoe UI Historic", 3, 14)); // NOI18N
        jLabel12.setText("Departamento:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Francisco Morazan", "Cortes", "Comayagua", " " }));

        jLabel13.setFont(new java.awt.Font("Segoe UI Historic", 3, 14)); // NOI18N
        jLabel13.setText("Fecha de Nacimiento:");

        jTextField4.setFont(new java.awt.Font("Segoe UI Historic", 3, 12)); // NOI18N
        jTextField4.setText("M O D I F I C A R");

        javax.swing.GroupLayout p_modcivilesLayout = new javax.swing.GroupLayout(p_modciviles);
        p_modciviles.setLayout(p_modcivilesLayout);
        p_modcivilesLayout.setHorizontalGroup(
            p_modcivilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_modcivilesLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(p_modcivilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_modcivilesLayout.createSequentialGroup()
                        .addComponent(mostrarid, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(p_modcivilesLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(163, 163, 163))
                    .addGroup(p_modcivilesLayout.createSequentialGroup()
                        .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tf_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))
                    .addGroup(p_modcivilesLayout.createSequentialGroup()
                        .addGroup(p_modcivilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_clave, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(p_modcivilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(p_modcivilesLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                                .addGroup(p_modcivilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_modcivilesLayout.createSequentialGroup()
                                        .addComponent(jCalendar2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(16, 16, 16)))
                                .addGap(56, 56, 56))
                            .addGroup(p_modcivilesLayout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        p_modcivilesLayout.setVerticalGroup(
            p_modcivilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_modcivilesLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(mostrarid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(p_modcivilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_modcivilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(p_modcivilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGroup(p_modcivilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_modcivilesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_clave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel12))
                    .addGroup(p_modcivilesLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jCalendar2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(p_modcivilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_modcivilesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_modcivilesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))))
        );

        jTabbedPane1.addTab("Modificacion Civiles", p_modciviles);

        jButton6.setText("Cerrar Sesion ❌");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout p_empleadoLayout = new javax.swing.GroupLayout(p_empleado);
        p_empleado.setLayout(p_empleadoLayout);
        p_empleadoLayout.setHorizontalGroup(
            p_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_empleadoLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
            .addGroup(p_empleadoLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addContainerGap())
        );
        p_empleadoLayout.setVerticalGroup(
            p_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_empleadoLayout.createSequentialGroup()
                .addGroup(p_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_empleadoLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(p_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(p_empleadoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton6)))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout empleadoLayout = new javax.swing.GroupLayout(empleado.getContentPane());
        empleado.getContentPane().setLayout(empleadoLayout);
        empleadoLayout.setHorizontalGroup(
            empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, empleadoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(p_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        empleadoLayout.setVerticalGroup(
            empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        p_civil.setBackground(new java.awt.Color(204, 255, 204));
        p_civil.setMinimumSize(new java.awt.Dimension(420, 420));
        p_civil.setPreferredSize(new java.awt.Dimension(720, 485));

        t_personal.setBackground(new java.awt.Color(255, 204, 204));

        jLabel16.setFont(new java.awt.Font("Segoe UI Historic", 3, 12)); // NOI18N
        jLabel16.setText("Informacion Personal:");

        table1_civil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre Completo", "Numero de Identidad", "Fecha de Nacimiento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table1_civil);

        jLabel17.setFont(new java.awt.Font("Segoe UI Historic", 3, 12)); // NOI18N
        jLabel17.setText("Tramites:");

        tablacivil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre Tramite", "Descripcion", "Fecha", "Numero de Identidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla2_empleado1.setViewportView(tablacivil);

        javax.swing.GroupLayout t_personalLayout = new javax.swing.GroupLayout(t_personal);
        t_personal.setLayout(t_personalLayout);
        t_personalLayout.setHorizontalGroup(
            t_personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(t_personalLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(t_personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tabla2_empleado1, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        t_personalLayout.setVerticalGroup(
            t_personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(t_personalLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabla2_empleado1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Informacion Personal", t_personal);

        p_gestion.setBackground(new java.awt.Color(255, 204, 204));

        jLabel18.setFont(new java.awt.Font("Segoe UI Emoji", 3, 12)); // NOI18N
        jLabel18.setText("N O M B R E :");

        jLabel19.setFont(new java.awt.Font("Segoe UI Historic", 3, 12)); // NOI18N
        jLabel19.setText("D E S C R I P C I O N:");

        jScrollPane2.setViewportView(tp_descripcion);

        jButton2.setFont(new java.awt.Font("Segoe UI Historic", 3, 12)); // NOI18N
        jButton2.setText("E N V I A R");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout p_gestionLayout = new javax.swing.GroupLayout(p_gestion);
        p_gestion.setLayout(p_gestionLayout);
        p_gestionLayout.setHorizontalGroup(
            p_gestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_gestionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(p_gestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_gestionLayout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(228, 228, 228))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_gestionLayout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(199, 199, 199))))
            .addGroup(p_gestionLayout.createSequentialGroup()
                .addGroup(p_gestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_gestionLayout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(tf_nombrecivil, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p_gestionLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_gestionLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(246, 246, 246))
        );
        p_gestionLayout.setVerticalGroup(
            p_gestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_gestionLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_nombrecivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Gestion de Tramites", p_gestion);

        jLabel14.setFont(new java.awt.Font("Sitka Subheading", 3, 24)); // NOI18N
        jLabel14.setText("B I E N V E N I D O :");

        jButton5.setFont(new java.awt.Font("Segoe UI Emoji", 3, 12)); // NOI18N
        jButton5.setText("Cerrar Sesion❌");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout p_civilLayout = new javax.swing.GroupLayout(p_civil);
        p_civil.setLayout(p_civilLayout);
        p_civilLayout.setHorizontalGroup(
            p_civilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_civilLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(p_civilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_civilLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_civilLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(18, 18, 18))
        );
        p_civilLayout.setVerticalGroup(
            p_civilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_civilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton5)
                .addGap(4, 4, 4)
                .addGroup(p_civilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout civilLayout = new javax.swing.GroupLayout(civil.getContentPane());
        civil.getContentPane().setLayout(civilLayout);
        civilLayout.setHorizontalGroup(
            civilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(civilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(civilLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(p_civil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        civilLayout.setVerticalGroup(
            civilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(civilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(civilLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(p_civil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login.setBackground(new java.awt.Color(204, 255, 204));
        login.setPreferredSize(new java.awt.Dimension(720, 485));
        login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sitka Display", 1, 48)); // NOI18N
        jLabel1.setText("L O G I N");
        login.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Sitka Text", 0, 24)); // NOI18N
        jLabel2.setText("Contraseña:");
        login.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));
        login.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 472, 30));

        jLabel3.setFont(new java.awt.Font("Sitka Text", 0, 24)); // NOI18N
        jLabel3.setText("Nombre Completo:");
        login.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));
        login.add(clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 470, 30));

        jButton1.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        jButton1.setText("Ingresar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        login.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, -1, -1));

        jButton3.setText("❌");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        login.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, -1, -1));

        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 721, 485));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mostraridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostraridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mostraridActionPerformed

    private void tf_claveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_claveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_claveActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jButton3MouseClicked

    private void p_empleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_empleadoMouseClicked

    }//GEN-LAST:event_p_empleadoMouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        empleado.setVisible(false);
        civil.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        empleado.setVisible(false);
        civil.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        int f = -1;
        String nc = nombre.getText();
        for (Usuario s : persona) {
            String nc2 = s.getNombre() + " " + s.getApellido();
            if (nc.equals(nc2) && clave.getText().equals(s.getClave()) && (s instanceof Empleados)) {
                f = 1;
            }
            if (nc.equals(nc2) && clave.getText().equals(s.getClave()) && (s instanceof Clientes)) {
                f = 2;
            }
            
        }
        if (f == -1) {
            JOptionPane.showMessageDialog(this, "Usuario no existe. ");
        }
        if (f == 1) {
            this.setVisible(false);
            empleado.pack();
            empleado.setVisible(true);
            jLabel11.setText(nc);
            nombre.setText("");
            clave.setText("");
            for (Usuario t : persona) {
                if (t instanceof Clientes) {
                    Object[] fila = {t.getNombre(), t.getNumidentidad(), t.getFecha()};
                    DefaultTableModel modelo = (DefaultTableModel) tablainfo.getModel();
                    modelo.addRow(fila);
                    tablainfo.setModel(modelo);
                    ArrayList<Tramites> tram = ((Clientes) t).getTramite();
                    for (Tramites trm : tram) {
                        Object[] fila2 = {trm.getNombre(), trm.getDescripcion(), trm.getFechaenvio(), trm.getNumidentidad()};
                        DefaultTableModel modelo2 = (DefaultTableModel) tablatrami.getModel();
                        modelo2.addRow(fila2);
                        tablatrami.setModel(modelo2);
                        
                    }
                    
                }
                
            }
            
        }
        if (f == 2) {
            this.setVisible(false);
            civil.pack();
            civil.setVisible(true);
            jLabel15.setText(nc);
            nombre.setText("");
            clave.setText("");
            for (Usuario t : persona) {
                if (t instanceof Clientes) {
                    String z = t.getNombre() + " " + t.getApellido();
                    if (z.equals(nc)) {
                        fulano = t;
                        Object[] fila = {t.getNombre(), t.getNumidentidad(), t.getFecha()};
                        DefaultTableModel modelo = (DefaultTableModel) table1_civil.getModel();
                        modelo.addRow(fila);
                        table1_civil.setModel(modelo);
                        ArrayList<Tramites> tram = ((Clientes) t).getTramite();
                        for (Tramites trm : tram) {
                            Object[] fila2 = {trm.getNombre(), trm.getDescripcion(), trm.getFechaenvio(), trm.getNumidentidad()};
                            DefaultTableModel modelo2 = (DefaultTableModel) tablacivil.getModel();
                            modelo2.addRow(fila2);
                            tablacivil.setModel(modelo2);
                            
                        }
                    }
                    
                }
                
            }
            
        }
        

    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        ((Clientes) fulano).getTramite().add(new Tramites(tf_nombrecivil.getText(), tp_descripcion.getText(), new Date(), "0204199807345"));
        Object[] fila2 = {tf_nombrecivil.getText(), tp_descripcion.getText(), new Date(), "0204199807345"};
        DefaultTableModel modelo2 = (DefaultTableModel) tablacivil.getModel();
        modelo2.addRow(fila2);
        tablacivil.setModel(modelo2);
        JOptionPane.showMessageDialog(this, "Tramite agregado con exito.");
        tf_nombrecivil.setText("");
        tp_descripcion.setText("");
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JframeExamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JframeExamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JframeExamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JframeExamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JframeExamen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame civil;
    private javax.swing.JPasswordField clave;
    private javax.swing.JFrame empleado;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private com.toedter.calendar.JCalendar jCalendar2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JPanel login;
    private javax.swing.JComboBox<String> mostrarid;
    private javax.swing.JTextField nombre;
    private javax.swing.JPanel p_civil;
    private javax.swing.JPanel p_empleado;
    private javax.swing.JPanel p_gestion;
    private javax.swing.JPanel p_infociviles;
    private javax.swing.JPanel p_modciviles;
    private javax.swing.JPanel t_personal;
    private javax.swing.JScrollPane tabla1_empleado;
    private javax.swing.JScrollPane tabla2_empleado1;
    private javax.swing.JTable tablacivil;
    private javax.swing.JTable tablainfo;
    private javax.swing.JTable tablatrami;
    private javax.swing.JScrollPane tablatramites;
    private javax.swing.JTable table1_civil;
    private javax.swing.JTextField tf_apellido;
    private javax.swing.JTextField tf_clave;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_nombrecivil;
    private javax.swing.JTextPane tp_descripcion;
    // End of variables declaration//GEN-END:variables
ArrayList<Usuario> persona = new ArrayList();
    Usuario fulano;
}
